# This is an example neoforge.mods.toml file for NeoForge 1.21.1
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL=""

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL=""
#displayURL=""
#logoFile="tinyredstone.png"
credits="Thanks for this mod goes to NeoForge and many mods who came before this."
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
